### ISSUE TITLE
Oceananigans-ClimaCore Rectangular Domain Prototype

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaEarth.jl#2]
(WIP)
# The Climate Modeling Alliance
### Purpose

Showcase a new design for coupling ClimaOcean and ClimaCore-based models. The current ClimaCoupler assumes ClimaCore-based underlying objects, whereas ClimaOcean assumes Oceananigans-based objects, making the two difficult to communicate with each other. With this effort we aim to
- unify the interfaces required to couple a component model to ClimaEarth, where the simulation will be setup
- present a prototype as the basis for CMIP (on which we can iterate based on feedback) 

### Cost/Benefits/Risks

- b: implements minimal features for ocean/atmosphere coupling 
- r: reasonable time investment

### People and Personnel

- Lead: @glwagner 
- Collaborators: @juliasloan25  @LenkaNovak  
- Reviewers: 

### Components

- ClimaEarth.jl
    - Abstract `Simulations` from Oceananigans and generalize for use by other models
    - Coupler functionality (for prototyping, keep here, and later will likely be moved to out)
        - regridding
            - stagerring (use Oceananigans)
            - FV-FE (Cartesian available in ClimaCore) 
        - masking and area fractions (perhaps not needed here?)
        - prescribed data readers (perhaps not needed here?)
        - flux calculation (NB: flux calculation outside of Atmos only really makes sense for one-timestep coupling)
        - flux accumulation
        - global checks
            - conservation checks: energy, water, mass, momentum
        - performance metrics 
        - I/O readers/writers (checkpoints, restarts, diagnostics)
- Atmosphere: a simple dry HeldSuarez that mimics the role of ClimaAmtos
- Ocean: ClimaOcean model setup using ClimaEarth Simulations

### Inputs

- ClimaCore HeldSuarez example
- Oceananigans exmaple
- ClimaCoupler functionality in src
- generalised interface for flux exchange (using ideas from
https://github.com/CliMA/ClimaCoupler.jl/issues/211 and [DoubleTrouble.jl](https://github.com/glwagner/DoubleTrouble.jl/blob/main/examples/two_dimensional_atmosphere_ocean.jl))

### Results and Deliverables

- [ ] Simulations in ClimaEarth.jl (QA: oceananigans runs as before)
- [ ] ClimaHeldSuarez with tracers and Simulations interface (QA: same output as the example in ClimaCore)
- [ ] Coupling prototype of the in a rectangular domain (QA: conservation and visual checks match)
- [ ] Detailed CMIP Roadmap (QA: approved by higher management)

### Task Breakdown And Schedule

 - ClimaHeldSuarez.jl
    - [x] migrate ClimaCore example to ClimaHeldSuarez.jl and ensure it runs 
    - [ ] implement ClimaHeldSuarezModel compatible with Simulations
    - [ ] write a CoupedModelComponent method dispatched AtmosModel
  
- Oceananigans.jl / ClimaOcean.jl
    - [ ] [Simulation refactor (move implementation to front of Oceananigans)](https://github.com/CliMA/Oceananigans.jl/issues/3088)
    - [ ] Modify Simulation creation process to use ClimaEarth
    - [ ] Develop ocean setup ready for coupling in ClimaOcean
    - [ ] write a CoupedModelComponent method dispatched on OceanModel
   
- ClimaEarth.jl
    - [ ] Setup CoupedModel, CoupedModelComponent, ...  interface
    - [ ] Setup regridding (staggering in Oceananigans, FV-SE in ClimaCore)
    - [ ] Develop EarthSystemModel coupling ClimaOcean.jl and ClimaHeldSuarez.jl
    - [ ] conservation checks
    - [ ] Migrate Simulations from Oceananigans
    - [ ] I/O + simple diagnostics

### CC
@tapios @simonbyrne @cmbengue

**Comment by tapios** [comment]
Could you please add a timeline and how would do what?

**Comment by LenkaNovak** [comment]
Will do - we're still working on the precise task breakdown, but after that we'll definitely put them in.
